version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/prime
permissions:
  - object: /home/ubuntu/prime
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: ubuntu